
image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-card-delivery.jar &
  - chmod +x gradlew # +x добавить права на (execute) выполнение файла (chmod (от англ. change mode) — команда для изменения прав доступа к файлам и каталогам, используемая в Unix-подобных операционных системах)

build_script:
  - ./gradlew test -Dselenium.headless=true --info  # запускаем тест, флаг --info позволяет выводить больше информации, стартуем Selenide в Headless-режиме